# Generated by Django 5.0.7 on 2024-07-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='calories',
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredients',
            field=models.CharField(default='', max_length=500),
        ),
    ]
